### PR TITLE
feat: gmacario solutions to days 04, 05, 06, 07, 08

### PR DESCRIPTION
**Pull request by gmacario**
## 📑 Description

The Title says it all.

Solution for Day 06, Part 2 is still WIP at the moment.

## ✅ Checks

- [x] My pull request adheres to the code style of this project
- [x] My code requires changes to the documentation
- [x] I have updated the documentation as required
- [x] All the tests have passed

### CODE REVIEW

**Comment by gmacario** [comment]
May I ask some kind fellow team member to please review and merge this PR?

**Review by davmacario — APPROVED** [review]
This PR is one of the reasons I hate Jupyter Notebooks

**Comment by gmacario** [comment]
Thanks for your review @davmacario.
Merging PR

Re:
> This PR is one of the reasons I hate Jupyter Notebooks

Could you please elaborate?

**Comment by davmacario** [comment]
> Could you please elaborate?

Git diff: +4880 -0

Lines of useful code ~300

**Comment by gmacario** [comment]
> > Could you please elaborate?
> 
> Git diff: +4880 -0
> 
> Lines of useful code ~300

Have you ever tried [this](https://stackoverflow.com/questions/37797709/convert-json-ipython-notebook-ipynb-to-py-file)

```bash
jupyter nbconvert --to script 'my-notebook.ipynb'
```

**Pull request merged**
